default_language_version:
  # default language version for each language
  python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace
        entry: trailing-whitespace-fixer
        language: python
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: static/
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=92, --max-complexity=6]
-   repo: local
    hooks:
    -   id: python-safety-dependencies-check
        name: safety
        description: This hook check common vulnerability on our package
        entry: safety
        args: [check pokemon/*.py,check pokedex/*.py, --full-report, --file]
        language: system
        files: issues
