# Generated by Django 4.2 on 2023-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokedexCreature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("type_1", models.CharField(max_length=100)),
                ("type_2", models.CharField(max_length=100)),
                ("total", models.PositiveSmallIntegerField()),
                ("hp", models.PositiveSmallIntegerField()),
                ("attack", models.PositiveSmallIntegerField()),
                ("defense", models.PositiveSmallIntegerField()),
                ("sp_atk", models.PositiveSmallIntegerField()),
                ("sp_def", models.PositiveSmallIntegerField()),
                ("speed", models.PositiveSmallIntegerField()),
                ("generation", models.PositiveSmallIntegerField()),
                ("legendary", models.BooleanField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
